2024-09-05 20:57:32,926 INFO    StreamThr :744511 [internal.py:wandb_internal():85] W&B internal server running at pid: 744511, started at: 2024-09-05 20:57:32.925783
2024-09-05 20:57:32,927 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status
2024-09-05 20:57:32,928 INFO    WriterThread:744511 [datastore.py:open_for_write():87] open: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/run-burqeowz.wandb
2024-09-05 20:57:32,929 DEBUG   SenderThread:744511 [sender.py:send():391] send: header
2024-09-05 20:57:32,933 DEBUG   SenderThread:744511 [sender.py:send():391] send: run
2024-09-05 20:57:33,514 INFO    SenderThread:744511 [dir_watcher.py:__init__():211] watching files in: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files
2024-09-05 20:57:33,514 INFO    SenderThread:744511 [sender.py:_start_run_threads():1200] run started: burqeowz with start time 1725537452.924956
2024-09-05 20:57:33,520 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: run_start
2024-09-05 20:57:33,529 DEBUG   HandlerThread:744511 [system_info.py:__init__():26] System info init
2024-09-05 20:57:33,529 DEBUG   HandlerThread:744511 [system_info.py:__init__():41] System info init done
2024-09-05 20:57:33,529 INFO    HandlerThread:744511 [system_monitor.py:start():194] Starting system monitor
2024-09-05 20:57:33,530 INFO    SystemMonitor:744511 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-05 20:57:33,530 INFO    HandlerThread:744511 [system_monitor.py:probe():214] Collecting system info
2024-09-05 20:57:33,530 INFO    SystemMonitor:744511 [interfaces.py:start():188] Started cpu monitoring
2024-09-05 20:57:33,531 INFO    SystemMonitor:744511 [interfaces.py:start():188] Started disk monitoring
2024-09-05 20:57:33,531 INFO    SystemMonitor:744511 [interfaces.py:start():188] Started gpu monitoring
2024-09-05 20:57:33,531 INFO    SystemMonitor:744511 [interfaces.py:start():188] Started memory monitoring
2024-09-05 20:57:33,532 INFO    SystemMonitor:744511 [interfaces.py:start():188] Started network monitoring
2024-09-05 20:57:33,544 DEBUG   HandlerThread:744511 [system_info.py:probe():152] Probing system
2024-09-05 20:57:33,545 DEBUG   HandlerThread:744511 [system_info.py:_probe_git():137] Probing git
2024-09-05 20:57:33,550 DEBUG   HandlerThread:744511 [system_info.py:_probe_git():145] Probing git done
2024-09-05 20:57:33,550 DEBUG   HandlerThread:744511 [system_info.py:probe():200] Probing system done
2024-09-05 20:57:33,550 DEBUG   HandlerThread:744511 [system_monitor.py:probe():223] {'os': 'Linux-6.8.0-40-generic-x86_64-with-glibc2.35', 'python': '3.11.0', 'heartbeatAt': '2024-09-05T11:57:33.544298', 'startedAt': '2024-09-05T11:57:32.859852', 'docker': None, 'cuda': None, 'args': ('--n_rollout_threads', '32', '--algorithm_name', 'mast', '--hidden_size', '128', '--map_name', 'MMM', '--use_wandb', '--group_name', 'mmm', '--experiment_name', 'v2'), 'state': 'running', 'program': '/home/hyunwoo/바탕화면/multi-agent/onpolicy/train_smac.py', 'codePathLocal': 'train_smac.py', 'codePath': 'onpolicy/train_smac.py', 'git': {'remote': 'https://github.com/singforai/multi-agent.git', 'commit': 'da9de1eb5cd9698b5c8a1a581c28052b3c38f8cf'}, 'email': 'singfor7012@gmail.com', 'root': '/home/hyunwoo/바탕화면/multi-agent', 'host': 'uos-desktop', 'username': 'hyunwoo', 'executable': '/home/hyunwoo/miniconda3/envs/smac/bin/python', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3288.5029583333344, 'min': 2200.0, 'max': 3700.0}, 'cpu_freq_per_core': [{'current': 3775.35, 'min': 2200.0, 'max': 3700.0}, {'current': 3783.013, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 4150.017, 'min': 2200.0, 'max': 3700.0}, {'current': 4716.211, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3594.613, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3592.557, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3695.364, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3748.633, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 4671.021, 'min': 2200.0, 'max': 3700.0}, {'current': 3572.561, 'min': 2200.0, 'max': 3700.0}, {'current': 3772.785, 'min': 2200.0, 'max': 3700.0}, {'current': 3592.697, 'min': 2200.0, 'max': 3700.0}, {'current': 3345.14, 'min': 2200.0, 'max': 3700.0}, {'current': 3684.232, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3596.191, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}], 'disk': {'/': {'total': 233.17998886108398, 'used': 135.27117156982422}}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}, {'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}], 'memory': {'total': 62.71548843383789}}
2024-09-05 20:57:33,550 INFO    HandlerThread:744511 [system_monitor.py:probe():224] Finished collecting system info
2024-09-05 20:57:33,550 INFO    HandlerThread:744511 [system_monitor.py:probe():227] Publishing system info
2024-09-05 20:57:33,550 DEBUG   HandlerThread:744511 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-05 20:57:34,515 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/conda-environment.yaml
2024-09-05 20:57:34,565 DEBUG   HandlerThread:744511 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-05 20:57:34,566 INFO    HandlerThread:744511 [system_monitor.py:probe():229] Finished publishing system info
2024-09-05 20:57:34,568 DEBUG   SenderThread:744511 [sender.py:send():391] send: files
2024-09-05 20:57:34,568 INFO    SenderThread:744511 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-09-05 20:57:34,606 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: python_packages
2024-09-05 20:57:34,606 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: python_packages
2024-09-05 20:57:34,606 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:57:34,606 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:57:34,608 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:57:34,826 DEBUG   SenderThread:744511 [sender.py:send():391] send: telemetry
2024-09-05 20:57:35,516 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/wandb-metadata.json
2024-09-05 20:57:35,518 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/output.log
2024-09-05 20:57:35,518 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/requirements.txt
2024-09-05 20:57:36,200 INFO    wandb-upload_0:744511 [upload_job.py:push():130] Uploaded file /tmp/tmpi8j1yqmuwandb/rrv7sdnz-wandb-metadata.json
2024-09-05 20:57:37,517 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/output.log
2024-09-05 20:57:37,949 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:57:43,615 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:57:44,609 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:57:49,606 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:57:49,606 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:57:50,167 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:57:54,608 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:57:55,611 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:00,611 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:04,606 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:58:04,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:58:04,647 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:58:05,889 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:06,528 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/config.yaml
2024-09-05 20:58:11,612 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:14,608 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:58:17,611 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:19,606 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:58:19,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:58:22,852 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:24,608 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:58:28,612 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:33,532 DEBUG   SystemMonitor:744511 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-05 20:58:33,534 DEBUG   SenderThread:744511 [sender.py:send():391] send: stats
2024-09-05 20:58:34,535 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:34,606 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:58:34,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:58:34,647 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:58:39,612 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:44,608 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:58:45,612 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:49,607 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:58:49,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:58:50,815 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:58:54,608 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:58:56,612 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:01,612 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:03,535 DEBUG   SenderThread:744511 [sender.py:send():391] send: stats
2024-09-05 20:59:04,607 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:59:04,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:59:04,648 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:59:07,095 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:12,613 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:14,609 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:59:18,613 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:19,607 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:59:19,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:59:23,907 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:24,609 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:59:29,613 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:33,536 DEBUG   SenderThread:744511 [sender.py:send():391] send: stats
2024-09-05 20:59:34,607 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:59:34,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:59:34,648 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:59:34,874 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:40,613 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:44,609 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:59:46,613 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:49,607 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:59:49,607 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:59:51,133 DEBUG   SenderThread:744511 [sender.py:send():391] send: exit
2024-09-05 20:59:51,133 INFO    SenderThread:744511 [sender.py:send_exit():598] handling exit code: 255
2024-09-05 20:59:51,133 INFO    SenderThread:744511 [sender.py:send_exit():600] handling runtime: 137
2024-09-05 20:59:51,133 INFO    SenderThread:744511 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-05 20:59:51,133 INFO    SenderThread:744511 [sender.py:send_exit():606] send defer
2024-09-05 20:59:51,134 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,134 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 0
2024-09-05 20:59:51,134 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,134 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 0
2024-09-05 20:59:51,134 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 1
2024-09-05 20:59:51,134 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,134 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 1
2024-09-05 20:59:51,135 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,135 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 1
2024-09-05 20:59:51,135 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 2
2024-09-05 20:59:51,135 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,135 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 2
2024-09-05 20:59:51,135 INFO    HandlerThread:744511 [system_monitor.py:finish():203] Stopping system monitor
2024-09-05 20:59:51,135 DEBUG   SystemMonitor:744511 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-05 20:59:51,135 DEBUG   SystemMonitor:744511 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-05 20:59:51,140 INFO    HandlerThread:744511 [interfaces.py:finish():200] Joined cpu monitor
2024-09-05 20:59:51,140 INFO    HandlerThread:744511 [interfaces.py:finish():200] Joined disk monitor
2024-09-05 20:59:51,317 ERROR   FileStreamThread:744511 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/singfor7012/smac/burqeowz/file_stream
NoneType: None
2024-09-05 20:59:51,321 INFO    HandlerThread:744511 [interfaces.py:finish():200] Joined gpu monitor
2024-09-05 20:59:51,321 INFO    HandlerThread:744511 [interfaces.py:finish():200] Joined memory monitor
2024-09-05 20:59:51,321 INFO    HandlerThread:744511 [interfaces.py:finish():200] Joined network monitor
2024-09-05 20:59:51,322 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,322 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 2
2024-09-05 20:59:51,322 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 3
2024-09-05 20:59:51,322 DEBUG   SenderThread:744511 [sender.py:send():391] send: stats
2024-09-05 20:59:51,323 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,323 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 3
2024-09-05 20:59:51,323 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,323 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 3
2024-09-05 20:59:51,323 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 4
2024-09-05 20:59:51,323 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,323 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 4
2024-09-05 20:59:51,323 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,323 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 4
2024-09-05 20:59:51,323 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 5
2024-09-05 20:59:51,323 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,323 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 5
2024-09-05 20:59:51,323 DEBUG   SenderThread:744511 [sender.py:send():391] send: summary
2024-09-05 20:59:51,324 INFO    SenderThread:744511 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-05 20:59:51,324 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,324 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 5
2024-09-05 20:59:51,324 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 6
2024-09-05 20:59:51,324 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,324 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 6
2024-09-05 20:59:51,324 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,324 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 6
2024-09-05 20:59:51,324 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 7
2024-09-05 20:59:51,324 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:59:51,324 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:51,324 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 7
2024-09-05 20:59:51,324 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:51,324 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 7
2024-09-05 20:59:51,556 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/wandb-summary.json
2024-09-05 20:59:52,131 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:59:52,923 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 8
2024-09-05 20:59:52,924 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:59:52,924 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:52,924 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 8
2024-09-05 20:59:52,924 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:52,924 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 8
2024-09-05 20:59:52,924 INFO    SenderThread:744511 [job_builder.py:build():443] Attempting to build job artifact
2024-09-05 20:59:52,925 INFO    SenderThread:744511 [job_builder.py:_get_source_type():572] is repo sourced job
2024-09-05 20:59:52,938 INFO    SenderThread:744511 [job_builder.py:build():548] adding wandb-job metadata file
2024-09-05 20:59:52,959 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 9
2024-09-05 20:59:52,959 DEBUG   SenderThread:744511 [sender.py:send():391] send: artifact
2024-09-05 20:59:52,960 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:52,961 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 9
2024-09-05 20:59:53,132 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:59:53,558 INFO    Thread-12 :744511 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/output.log
2024-09-05 20:59:53,837 ERROR   SenderThread:744511 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:59:53,837 ERROR   SenderThread:744511 [internal_api.py:execute():350] {"errors":[{"message":"failed to find run smac/burqeowz","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-09-05 20:59:53,837 ERROR   SenderThread:744511 [sender.py:send_artifact():1551] send_artifact: failed for artifact "job/job-https___github.com_singforai_multi-agent.git_onpolicy_train_smac.py": It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:59:53,837 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:53,837 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 9
2024-09-05 20:59:53,837 INFO    SenderThread:744511 [dir_watcher.py:finish():358] shutting down directory watcher
2024-09-05 20:59:54,559 INFO    SenderThread:744511 [dir_watcher.py:finish():388] scan: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files
2024-09-05 20:59:54,559 INFO    SenderThread:744511 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/conda-environment.yaml conda-environment.yaml
2024-09-05 20:59:54,559 INFO    SenderThread:744511 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/requirements.txt requirements.txt
2024-09-05 20:59:54,559 INFO    SenderThread:744511 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/config.yaml config.yaml
2024-09-05 20:59:54,561 INFO    SenderThread:744511 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/wandb-metadata.json wandb-metadata.json
2024-09-05 20:59:54,561 INFO    SenderThread:744511 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/output.log output.log
2024-09-05 20:59:54,562 INFO    SenderThread:744511 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/wandb-summary.json wandb-summary.json
2024-09-05 20:59:54,563 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 10
2024-09-05 20:59:54,563 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:59:54,564 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:54,564 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 10
2024-09-05 20:59:54,565 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:54,565 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 10
2024-09-05 20:59:54,565 INFO    SenderThread:744511 [file_pusher.py:finish():169] shutting down file pusher
2024-09-05 20:59:54,745 ERROR   wandb-upload_0:744511 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:59:54,745 ERROR   wandb-upload_0:744511 [internal_api.py:execute():350] {"errors":[{"message":"run smac/burqeowz not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:59:54,745 ERROR   Thread-11 (_thread_body):744511 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:59:54,752 ERROR   wandb-upload_1:744511 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:59:54,752 ERROR   wandb-upload_1:744511 [internal_api.py:execute():350] {"errors":[{"message":"run smac/burqeowz not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:59:54,752 ERROR   Thread-11 (_thread_body):744511 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/requirements.txt
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:59:54,867 ERROR   wandb-upload_2:744511 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:59:54,867 ERROR   wandb-upload_2:744511 [internal_api.py:execute():350] {"errors":[{"message":"run smac/burqeowz not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:59:54,867 ERROR   wandb-upload_3:744511 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:59:54,867 ERROR   wandb-upload_3:744511 [internal_api.py:execute():350] {"errors":[{"message":"run smac/burqeowz not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:59:54,868 ERROR   Thread-11 (_thread_body):744511 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/config.yaml
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:59:54,868 ERROR   wandb-upload_4:744511 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:59:54,868 ERROR   Thread-11 (_thread_body):744511 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/output.log
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:59:54,868 ERROR   wandb-upload_4:744511 [internal_api.py:execute():350] {"errors":[{"message":"run smac/burqeowz not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:59:54,869 ERROR   Thread-11 (_thread_body):744511 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:59:55,070 INFO    Thread-11 (_thread_body):744511 [sender.py:transition_state():626] send defer: 11
2024-09-05 20:59:55,071 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:55,071 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 11
2024-09-05 20:59:55,071 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:55,071 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 11
2024-09-05 20:59:55,071 INFO    SenderThread:744511 [file_pusher.py:join():175] waiting for file pusher
2024-09-05 20:59:55,071 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 12
2024-09-05 20:59:55,071 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:55,071 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 12
2024-09-05 20:59:55,072 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:55,072 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 12
2024-09-05 20:59:55,072 INFO    SenderThread:744511 [file_stream.py:finish():601] file stream finish called
2024-09-05 20:59:55,133 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:59:55,263 ERROR   FileStreamThread:744511 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/singfor7012/smac/burqeowz/file_stream
NoneType: None
2024-09-05 20:59:55,447 INFO    SenderThread:744511 [file_stream.py:finish():605] file stream finish is done
2024-09-05 20:59:55,447 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 13
2024-09-05 20:59:55,447 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:59:55,447 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:55,447 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 13
2024-09-05 20:59:55,448 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:55,448 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 13
2024-09-05 20:59:55,448 INFO    SenderThread:744511 [sender.py:transition_state():626] send defer: 14
2024-09-05 20:59:55,448 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:59:55,448 INFO    HandlerThread:744511 [handler.py:handle_request_defer():184] handle defer: 14
2024-09-05 20:59:55,448 DEBUG   SenderThread:744511 [sender.py:send():391] send: final
2024-09-05 20:59:55,449 DEBUG   SenderThread:744511 [sender.py:send():391] send: footer
2024-09-05 20:59:55,449 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: defer
2024-09-05 20:59:55,449 INFO    SenderThread:744511 [sender.py:send_request_defer():622] handle sender defer: 14
2024-09-05 20:59:55,449 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:59:55,450 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:59:55,450 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: server_info
2024-09-05 20:59:55,450 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:59:55,450 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: server_info
2024-09-05 20:59:55,452 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: get_summary
2024-09-05 20:59:55,452 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: sampled_history
2024-09-05 20:59:55,453 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:59:55,638 DEBUG   SenderThread:744511 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:59:55,639 INFO    MainThread:744511 [wandb_run.py:_footer_history_summary_info():4078] rendering history
2024-09-05 20:59:55,639 INFO    MainThread:744511 [wandb_run.py:_footer_history_summary_info():4110] rendering summary
2024-09-05 20:59:55,639 INFO    MainThread:744511 [wandb_run.py:_footer_sync_info():4037] logging synced files
2024-09-05 20:59:55,640 DEBUG   HandlerThread:744511 [handler.py:handle_request():158] handle_request: shutdown
2024-09-05 20:59:55,640 INFO    HandlerThread:744511 [handler.py:finish():884] shutting down handler
2024-09-05 20:59:56,451 INFO    WriterThread:744511 [datastore.py:close():296] close: /home/hyunwoo/바탕화면/multi-agent/results/smac/MMM/mast/v2/wandb/run-20240905_205732-burqeowz/run-burqeowz.wandb
2024-09-05 20:59:56,639 INFO    SenderThread:744511 [sender.py:finish():1631] shutting down sender
2024-09-05 20:59:56,639 INFO    SenderThread:744511 [file_pusher.py:finish():169] shutting down file pusher
2024-09-05 20:59:56,639 INFO    SenderThread:744511 [file_pusher.py:join():175] waiting for file pusher
